name: Create Release Workflow

on:
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Set Release Version
        run: echo "RELEASE_VERSION=20" >> $GITHUB_ENV

      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Fetch JIRA Ticket Name
        id: jira
        run: |
          response=$(curl -s -u andrewswhitehouse@gmail.com:${{ secrets.JIRA_TOKEN }} \
            -X GET "https://andrewswhitehouse.atlassian.net/rest/api/3/issue/TRAC-1" \
            -H "Accept: application/json")

          ticket_name=$(echo $response | jq -r '.fields.summary')
          echo "JIRA_TICKET_NAME=$ticket_name" >> $GITHUB_ENV
        env:
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}

      - name: Debug release version
        run: echo "Creating release for version ${{ env.RELEASE_VERSION }}"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ env.RELEASE_VERSION }}"
          release_name: "Release v${{ env.RELEASE_VERSION }}"
          body: "This is the release for version ${{ env.RELEASE_VERSION }}."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

