name: Create Release Workflow

on:
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Debug release version
        run: echo "Creating release for version 20"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: "test tag"
          release_name: "test release"
          body: "A release"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
