name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Enter release version'
        required: true

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Debug release version
        run: echo "Creating release for version: $RELEASE_VERSION"
        env:
          RELEASE_VERSION: ${{ github.event.inputs.release_version }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: "${{ github.event.inputs.release_version }}"
          release_name: "${{ github.event.inputs.release_version }}"
          body: "Release for version ${{ github.event.inputs.release_version }}"
          draft: false
          prerelease: false
        env:
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}

